apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: khaled
  labels:
    app: db 
spec:
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 20 
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db 
    spec:
      containers:
      - name: db-deployment
        image: harbor.dev.afsmtddso.com/khaled-devsecops/db:64edffa-1d6f44f 
        ports:
        - containerPort: 5432 
        envFrom:
        - secretRef:
            name: db-secret
